 
###
GET http://localhost:3000/carrito
 

###
GET http://localhost:3000/carrito/1


###
POST http://localhost:3000/carrito
Content-Type: application/json

{
     "id_usuario":"1",
    "estado":"1" 
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
     "email":"mauro.julian.ayala@gmail.com",
    "pass":"1234"
}


###
PUT http://localhost:3000/carrito/5
Content-Type: application/json
 

###
DELETE http://localhost:3000/carrito/4

###
POST http://localhost:3000/detalle
Content-Type: application/json

{
    "id_producto":"3",
    "cantidad":"3",
    "id_carrito":"2",
    "precio":"200"

}

###
PUT http://localhost:3000/detalle/1
Content-Type: application/json
 
{
    "cantidad":"20"
} 

###
PUT http://localhost:3000/detalle/1
Content-Type: application/json
 
{
    "cantidad":"0"
}
 

###
GET http://localhost:3000/detalle/1
Content-Type: application/json
 